#include <stdio.h>
#include <stdlib.h>
#include <iostream>
#include <string.h>
#include <string>
#include <sstream>
#include <algorithm>
#include <cassert>
#include <queue>
#include <semaphore.h>
#include <pthread.h>
#include <sys/times.h>
#include <time.h>
#include <sys/resource.h>
#include <unistd.h>
#include <signal.h>
#include <map>
#include <vector>