#include <iostream>
#include <string>
#include <cstring>
#include <cstdlib>
#include <vector>
#include <sstream>
#include <iterator>
#include <stdio.h>
#include <algorithm>
#include <unistd.h>
#include <sys/wait.h>
#include <signal.h>
#include <sys/times.h>
#include <time.h>
#include <stdint.h>
#include <sys/resource.h>
#include <map>
#include <fcntl.h>
#include <fstream>